FROM python:3.9-slim-buster
LABEL name="{{project_name}}" version="1.0.0"

ENV POETRY_VIRTUALENVS_CREATE 0
ENV POETRY_NO_INTERACTION 1
ENV POETRY_HOME "$HOME/.poetry"
ENV PATH="$POETRY_HOME/bin:$PATH"
ENV PYTHONPYCACHEPREFIX /.pycache
ENV DJANGO_DEBUG 0

# Let all *.pyc files stay within the container, for Python >= 3.8
RUN mkdir -p $PYTHONPYCACHEPREFIX

# Use non-interactive frontend for debconf
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# Install system requirements
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential gettext libpq-dev zlib1g-dev libjpeg62-turbo-dev curl && \
    rm -rf /var/lib/apt/lists/*

RUN pip install -U pip setuptools wheel poetry

COPY ["backend/pyproject.toml", "backend/poetry.lock", "/"]

# Install all dependencies from poetry.lock (dev included by default)
RUN poetry install --no-dev

# Copy code
COPY ./backend /app

# Set the default directory where CMD will execute
WORKDIR /app

RUN mkdir -p /staticfiles

# Add non-root user for the app
RUN adduser --disabled-password --gecos "" --shell /bin/false app
# Switch to non-root user for the app
RUN chown -R app /staticfiles
USER app

RUN /app/manage.py collectstatic --noinput

CMD gunicorn wsgi:application --workers 2
