version: '3.4'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend-dev
    env_file: .env
    volumes:
      - "./frontend:/app"
      - "./backend:/backend"
      - ".data/node_modules:/app/node_modules"
      - ".data/yarn:/usr/local/share/.cache/yarn"
    command:
      - "yarn && yarn dev"

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend-dev
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app"
      - "./backend/pyproject.toml:/pyproject.toml"
      - "./backend/poetry.lock:/poetry.lock"
      - "./frontend/_build/styles:/app/static/css"
      - "./.data/static:/backend/static"
      - "./.data/media:/backend/media"
      - "./.data/staticfiles:/staticfiles"
      - "./.data/.ipython:/root/.ipython"
      - "./.data/pycache/mypy:/root/.cache/mypy"
      - "./.data/pycache/pytest:/root/.cache/pytest"
      - "./.data/pycache/ruff:/root/.cache/ruff"
      - "./.data/pycache/coverage:/root/.cache/coverage"
      - "${DPT_POETRY_CACHE_DIR:-./.data/pycache/pypoetry}:/root/.cache/pypoetry"
      - "${DPT_PIP_CACHE_DIR:-./.data/pycache/pip}:/root/.cache/pip"
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPYCACHEPREFIX: "../__pycache__"
    command: python manage.py runserver 0.0.0.0:8000 --nostatic
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

  postgres:
    image: postgres:14
    # Comment in the following lines to connect to your Dockerized instance of Postgres from your host machine.
    # Change the host port (before colon) if you have a local instance of Postgres running on that port.
    # ports:
    #     - "5432:5432"
    volumes:
      - ".data/postgres:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d projectdb"]
      interval: 1s
      timeout: 1s
      retries: 30
    environment:
      # credentials taken from .env file
      POSTGRES_DB: "${DATABASE_NAME:-projectdb}"
      POSTGRES_USER: "${DATABASE_USER:-dbuser}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD:-dbpass}"
